export default [
  {
    id: 1,
    dataServico: "23/10",
    hora: "10:00",
    venda: "25L",
    motorista: "Miguel",
    pagamento: "Pago",
  },
  {
    id: 2,
    dataServico: "23/10",
    hora: "10:00",
    venda: "25L",
    motorista: "Miguel",
    pagamento: "Pago",
  },
  {
    id: 3,
    dataServico: "23/10",
    hora: "10:00",
    venda: "25L",
    motorista: "Miguel",
    pagamento: "Pago",
  },
  {
    id: 4,
    dataServico: "23/10",
    hora: "10:00",
    venda: "25L",
    motorista: "Miguel",
    pagamento: "Pago",
  },
  {
    id: 5,
    dataServico: "23/10",
    hora: "10:00",
    venda: "25L",
    motorista: "Miguel",
    pagamento: "Pago",
  },
  {
    id: 6,
    dataServico: "23/10",
    hora: "10:00",
    venda: "25L",
    motorista: "Miguel",
    pagamento: "Pago",
  },
  {
    id: 7,
    dataServico: "23/10",
    hora: "10:00",
    venda: "25L",
    motorista: "Miguel",
    pagamento: "Pago",
  },
];
